# escape=`

FROM lacledeslan/gamesvr-svencoop

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV IMAGE="gamesvr-svencoop-freeplay"

HEALTHCHECK NONE

COPY ./dist /app/svencoop/

# UPDATE USERNAME
RUN usermod -l SvenCoOpFreeplay SvenCoOp

USER SvenCoOpFreeplay

WORKDIR /app/
